/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE voucherBase PLEASE EDIT ../voucher.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Area } from '../area';
import { Corso } from '../corso';
import { Dipendente } from '../dipendente';
import { Esame } from '../esame';

/**
 * This is the model of voucher object
 *
 */
export class VoucherBase {

    constructor() { }

    public _id: string;
    public codiceVoucher?: string;
    public dataAssegnazione?: Date;
    public dataScadenza?: Date;
    public note?: string;
    public tipologiaAcquisto?: string;
    // Relations area
    public area: Area | string;
    // Relations corso
    public corso: Corso | string;
    // Relations dipendente
    public dipendente: Dipendente | string;
    // Relations esame
    public esame: Esame | string;
}
