// INSERT HERE YOURS SCHEMA'S CUSTOMIZATIONS

const db_GESTIONE_CERTIFICATI_db = require('./GESTIONE_CERTIFICATI_db_schema.js');
const db_GESTIONE_CERTIFICATI_db_schema = db_GESTIONE_CERTIFICATI_db.schema;
